# Generated by Django 4.2.7 on 2025-11-22 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Deal value in currency",
                        max_digits=12,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("prospecting", "Prospecting"),
                            ("qualification", "Qualification"),
                            ("proposal", "Proposal"),
                            ("negotiation", "Negotiation"),
                            ("closed_won", "Closed Won"),
                            ("closed_lost", "Closed Lost"),
                        ],
                        default="prospecting",
                        max_length=20,
                    ),
                ),
                (
                    "probability",
                    models.IntegerField(
                        default=50, help_text="Probability of closing (0-100%)"
                    ),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "db_table": "deals",
                "ordering": ["-created_at"],
            },
        ),
    ]
