"""
Admin configuration for Lead model.
"""
from django.contrib import admin
from .models import Lead


@admin.register(Lead)
class LeadAdmin(admin.ModelAdmin):
    """
    Admin interface for managing leads.
    """
    list_display = ['name', 'email', 'company', 'status', 'category', 'score', 'assigned_to', 'created_at']
    list_filter = ['status', 'category', 'source', 'created_at']
    search_fields = ['name', 'email', 'company']
    ordering = ['-created_at']
    readonly_fields = ['score', 'category', 'created_at', 'updated_at']
    
    fieldsets = (
        ('Basic Information', {
            'fields': ('name', 'email', 'phone', 'company', 'website')
        }),
        ('Lead Details', {
            'fields': ('status', 'source', 'description', 'assigned_to')
        }),
        ('AI Generated Fields', {
            'fields': ('score', 'category'),
            'description': 'These fields are automatically generated by AI'
        }),
        ('Timestamps', {
            'fields': ('created_at', 'updated_at')
        }),
    )
