# Generated by Django 4.2.7 on 2025-11-22 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("lost", "Lost"),
                            ("converted", "Converted"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("referral", "Referral"),
                            ("social_media", "Social Media"),
                            ("email_campaign", "Email Campaign"),
                            ("cold_call", "Cold Call"),
                            ("other", "Other"),
                        ],
                        default="website",
                        max_length=30,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        default=0, help_text="AI-generated lead score (0-100)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("hot", "Hot"), ("warm", "Warm"), ("cold", "Cold")],
                        default="cold",
                        help_text="AI-generated category (Hot/Warm/Cold)",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="leads_email_554d9f_idx"),
                    models.Index(fields=["status"], name="leads_status_94f025_idx"),
                    models.Index(fields=["category"], name="leads_categor_01d7dc_idx"),
                ],
            },
        ),
    ]
