# Generated by Django 5.2.8 on 2025-11-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("sales_manager", "Sales Manager"),
                    ("account_manager", "Account Manager"),
                    ("bde", "Business Development Exec"),
                    ("pre_sales", "Pre-Sales Consultant"),
                    ("developer", "Developer / Technical Staff"),
                ],
                default="developer",
                max_length=20,
            ),
        ),
    ]
