# Generated by Django 4.2.7 on 2025-11-22 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
        ("leads", "0001_initial"),
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="leads.lead",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="polarity",
            field=models.FloatField(
                default=0.0, help_text="Sentiment polarity (-1 to 1)"
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="subjectivity",
            field=models.FloatField(
                default=0.0, help_text="Sentiment subjectivity (0 to 1)"
            ),
        ),
    ]
